# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-26 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import superorder.apps.restaurant_setting.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_auto_20171121_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('intro', models.TextField()),
                ('src', models.ImageField(blank=True, null=True, upload_to=superorder.apps.restaurant_setting.helpers.get_file_path)),
                ('category', models.CharField(max_length=50)),
                ('top10', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Restaurant')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
