# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
