# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20171207_1313'),
        ('restaurant_setting', '0003_auto_20171206_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('creation_date', models.DateTimeField()),
                ('peopleNum', models.PositiveIntegerField()),
                ('tableNum', models.PositiveIntegerField()),
                ('bell', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Restaurant')),
            ],
            options={
                'ordering': ('creation_date',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('scount', models.PositiveIntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_setting.Food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_setting.Order')),
            ],
        ),
    ]
