# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-19 04:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_setting', '0005_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bellTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
