# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_restaurant_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='rest_icon'),
        ),
    ]
