# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_restaurant_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='icon',
            new_name='logo',
        ),
    ]
