# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import superorder.apps.authentication.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20171121_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=superorder.apps.authentication.helpers.get_file_path),
        ),
    ]
