# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_restaurant_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workat', to=settings.AUTH_USER_MODEL),
        ),
    ]
